### ISSUE TITLE
Issue with Pretrained Models in MoLFormer-data - Required Checkpoint Files Missing

### ISSUE THREAD

**Issue by Xinheng-He** [IBM/molformer#10]
I am attempting to use the provided model to generate vectors for our molecular datasets. However, I have encountered an issue with the Jupyter Notebook provided. It seems to require linear_rotary.ckpt and full_rotary.ckpt checkpoint files which I could not find in the pre-trained model zip located at: https://ibm.ent.box.com/v/MoLFormer-data.
The downloaded zip contains checkpoint files like N-Step-Checkpoint_3_30000.ckpt, but none of these could be loaded as the linear_rotary.ckpt or full_rotary.ckpt that the notebook is expecting.
The absence of these files has caused some difficulty in reproducing the results as outlined in your guide. Your assistance in this matter would be greatly appreciated. If there are alternative sources for these checkpoint files, could you please point me to them? Or, if there are necessary steps I am missing to generate or convert the provided checkpoint files, could you guide me through them?
Thank you in advance for your assistance.

**Comment by YehudaItkin** [comment]
The issue is still exists

**Comment by niemasd** [comment]
Pinging this as well. Perhaps the GitHub Issue should be reopened? We're unable to use the pre-trained model on our end as well

**Comment by hoffmansc** [comment]
This is now clarified in the README. We only provide one set of pretrained checkpoints.
