### ISSUE TITLE
Inaccurate reproduction results on QM9

### ISSUE THREAD

**Issue by Park-ing-lot** [IBM/molformer#15]
When I finetune the model from checkpoint "N-Step-Checkpoint_3_30000.ckpt",
the reproduction results are much higher than them report in the paper.

For example, I got 1.4575 on u0 task, while the reported result on the same task is 0.3211.
I have checked the finetune code several times, I cannot find issues.

Is there anyone who get similar results to the reported ones on any regression task?

**Comment by hoffmansc** [comment]
Please see the README. The provided checkpoints are for 10% ZINC + 10% PubChem, not the full MoLFormer-XL weights.
