### ISSUE TITLE
No module named 'fast_trans_code'

### ISSUE THREAD

**Issue by mapengsen** [IBM/molformer#2]
ModuleNotFoundError: No module named 'fast_trans_code'

**Comment by huihuiqu** [comment]
I think this is a customized fast-transformers. Please also update this dependency

**Comment by mapengsen** [comment]
> I think this is a customized fast-transformers. Please also update this dependency

I don't understand what you mean. Could you be more specific?
Is it because the author of the code has not completely updated it?

**Comment by huihuiqu** [comment]
> > I think this is a customized fast-transformers. Please also update this dependency
> 
> I don't understand what you mean. Could you be more specific? Is it because the author of the code has not completely updated it?

That's my understanding. I think that they modify the fast-transformer package's source code. We need to have the updated code.

**Comment by ink-pad** [comment]
@huihuiqu / @mapengsen : 

@mapengsen is right. We have a modified version of [fast-transformer](https://github.com/idiap/fast-transformers). Since it requires a intricate internal approval process to "reshare" existing code, we are preparing a documentation to describe the changes you would need to make this work. We will keep this issue open and update further.

**Comment by mapengsen** [comment]
> @huihuiqu / @mapengsen :
> 
> @mapengsen is right. We have a modified version of [fast-transformer](https://github.com/idiap/fast-transformers). Since it requires a intricate internal approval process to "reshare" existing code, we are preparing a documentation to describe the changes you would need to make this work. We will keep this issue open and update further.

Please update as soon as possible, thank you very much！

**Comment by gokceuludogan** [comment]
Is there any progress on this issue?

**Comment by ink-pad** [comment]
@huihuiqu / @mapengsen / @gokceuludogan - 

We have updated the new changes in the latest commit and made the necessary changes. Please reopen the issue if you have more questions!
